blank_issues_enabled: false
contact_links:
  - name: 💬 Q&A / Discussion
    url: https://github.com/dsrtartweb10-prog/my-full-browser/discussions
    about: Ask questions and discuss general ideas about DSRT Browser here.
